import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2d92cc67c9fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('routes', 'date',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Date(),
                    existing_nullable=False,
                    postgresql_using="date::date")
    op.create_foreign_key(None, 'routes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.alter_column('routes', 'date',
                    existing_type=sa.Date(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.drop_column('routes', 'user_id')
    # ### end Alembic commands ###
