"""Remove unique constraint from route name

Revision ID: 44de62e6fa01
Revises: 2d92cc67c9fe
Create Date: 2024-12-28 11:57:45.575273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44de62e6fa01'
down_revision: Union[str, None] = '2d92cc67c9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_routes_name', table_name='routes')
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.create_index('ix_routes_name', 'routes', ['name'], unique=True)
    # ### end Alembic commands ###
